# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name sumCpp
#' @rdname sumR
#'
#' @examples
#' sumCpp(1, 2)
#'
#' @details \code{sumCpp} is an implementation using the Rcpp interface.
#'
#' @export
sumCpp <- function(x, y) {
    .Call('sumR_sumCpp', PACKAGE = 'sumR', x, y)
}

